collections:
  posts:
    output: true
    permalink: /posts/:year/:slug
  archives: 
    output: true

_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide

  column-sizes:
    col-6: One Half
    col-12: Full Width
    col-4: One Third
    col-3: One Quarter
    col-6_sm-12: One Half Desktop (Stacked)
    col-4_sm-12: One Third Desktop (Stacked)
    col-3_sm-12: One Quarter Desktop (Stacked)
    
  buttons:
    button-special: Button Special
    button-rojo: Button Rojo
    button-celeste: Button Celeste
    button-fresa: Button Fresa
    button-amarillo: Button Amarillo
    button-negro: Button Negro
    button-beige: Button Beige