general:
  logo-white_image: /images/hakau-icon24.png
  logo-dark_image: /images/hakau-icon25.png
  logo-size: 45%
  mobile-logo_image: /images/hakau-icon4.png
  mobile-logo-size: 60%
  explore-logo-size: 50%
technical:
  adobe-fonts-embed: <link rel="stylesheet" href="https://use.typekit.net/hqq0vnm.css">
seo:
  site_name: Hakau | Sustainable Fair Trade E-commerce
  title: Hakau | Sustainable Fair Trade E-commerce
  description:
  keywords:
  - sustainable ecommerce